name: Build checking for production area

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.10.0"
      - name: Install dependencies
        run: npm install
      - name: Run build
        run: npm run build
